---

- name: Show Commands Playbook
  hosts: all
  gather_facts: no
  #connection: local

  tasks:
  - name: Get Login credentials
    include_vars: /var/lib/awx/projects/_14__simple/template/access.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

  - name: Name
    ios_command: 
      commands: show version
      provider: "{{ provider }}"
      authorize: yes
      commands:
         #"CLI" is the variable for any show command on the $prompt, using -e "cli='show command'"
      - "{{ cli }}"

      
    register: output

  - debug: var=output.stdout_lines


...
